version: "3.6"

services:
  app:
    build: ./docker/app
    image: laravel/app:1
    ports:
      - 8000:8000
    volumes:
      - ./server:/var/www:cached
    working_dir: /var/www

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./server:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    build: docker/db/
    image: laravel/db:1
    env_file: .env
    volumes:
      - "./mysql-data:/var/lib/mysql"
    ports:
      - 3306:3306
    command: --innodb-use-native-aio=0
